server:
  port: 10081

boot:
  sample:
    security:
      oauth2:
        store-type: jwt
        jwt-signing-key: sample
        clients:
        - client-id: sample
          client-secret: 123456
          access-token-validity-seconds: 7200
          refresh-token-validity-seconds: 1296000
        - client-id: sample2
          client-secret: 123456
